### PR TITLE
SNI-2881: code fix applied and successfully tested locally

### PR DESCRIPTION
**Pull request by javimarinc96**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SNI-2881

### Change description ###

Added a new case on the code when no hearing center is present in a without-hearing decision appeal at the moment of end appeal in the case decision without a hearing has been made first and finally, the appeal has been ended

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

### CODE REVIEW

**Review by jip1984 — DISMISSED** [review]
LGTM

**Review by mcareyma — APPROVED** [review]
Javier has explained the convoluted reasoning, which I now understand, and how a bit of the code is expecting an address that in this particular case is not there.

**Review by filippo-possenti-version1 — APPROVED** [review]

**Comment by JamesBoadi** [comment]
LGTM

**Review by jip1984 — APPROVED** [review]
LGTM

**Pull request merged**
